apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            {{ if .Values.autoscaling.enabled }}
            name: keda-add-ons-http-interceptor-proxy
            port:
              number: {{ .Values.interceptorPort }}
            {{- else }}
            name: django
            port:
              number: {{ .Values.port }}
            {{- end }}
